version: "3"

services:
  redis:
    image: "redis"
    expose:
      - 6379
    volumes:
      - nodejs-cache-http:/db

  app:
    build: .
    ports:
      - 8080:8080
    links:
      - redis
    environment:
      - PORT=8080

volumes:
  nodejs-cache-http:
