version: "3"

services:
  redis:
    image: "redis"
    container_name: db
    expose:
      - 6379
    volumes:
      - nodejs-cache-http:/db

  app:
    build: .
    ports:
      - 8080:8080
    container_name: client
    links:
      - redis
volumes:
  nodejs-cache-http:
